// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahvperrkqntxrqlqpauk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFodnBlcnJrcW50eHJxbHFwYXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTA3NTMsImV4cCI6MjA3MTIyNjc1M30.YuImn7VwUM1OwJPn1RAbRH23KYH5nrACg3739ZIqPCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});